### ISSUE TITLE
supposed working

### ISSUE THREAD

**Issue by jampack** [xparthx/Larevel-echo-with-socket.io#1]
is it supposed to update the all articles page on the run when we post a new article right? if yes then its not,
queue:work active echo server active..

**Comment by parth-vora-7** [comment]
@akkhan20, well it depends on the requirements. I have just appended the new article on top of the other existed articles for better performance. Suppose there are 100 articles on the page, then it will make a huge impact on the performance, so as per my opinion it is better to append the new one only. But if you want to update all, then it is not hard to achieve.

Thanks

**Comment by jampack** [comment]
@xparthx i wanted to say that its not appending any articles at all, there must be a mistake on my side in that case but actually i need help with private channels and in your example you have implemented public channel, though u have already done an excellent job but when i changed channels to private in your project it was responding like my project:
`Client can not be authenticated, got HTTP status 404
`

**Comment by parth-vora-7** [comment]
Ok no issue, I'll make an private channel demo whenever I get some time.

On 20 Mar 2017 11:08 p.m., "Muhammad Akbar" <notifications@github.com>
wrote:
>
> @xparthx i wanted to say that its not appending any articles at all,
there must be a mistake on my side in that case but actually i need help
with private channels and in your example you have implemented public
channel, though u have already done an excellent job but when i changed
channels to private in your project it was responding like my project:

**Comment by jampack** [comment]
if you can explain in few lines what needs to be different when channel is private i will try it myself, actually im modifying this project: [https://github.com/nahid/talk](url) to add on premises chat server to the package as it uses pusher which is not free after a certain limit.

**Comment by parth-vora-7** [comment]
@akkhan20, Sorry it is bit late, but worth a shot

I have created a new chat app which uses all three types of channels(private, public & presence):
https://github.com/xparthx/laravel-realtime-chat 

Thanks
